version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:50873"
networks:
  default:
    name: dockernetwork
    external: true